var express = require('express');
var route = express.Router();
var problem = require('./../controller/problem');
var location = require('../controller/location');
var patient = require('../controller/patient');
var charttype = require('../controller/charttype');
var cpt = require('../controller/cpt');
var social = require('../controller/social');
var family = require('../controller/family');
var note = require('../controller/note');
var meds = require('../controller/problem/meds');
var dynamic = require('../controller/problem/dynamic');
var macro = require('../controller/macro');
var user = require('../controller/user');
var admin = require('../controller/admin');
function register(req,res)
{
    route.get('/problem/get',problem.get);
    route.get('/problem/common',problem.common);
    route.get('/problem/favourite',problem.favourite);
    route.get('/problem/getrelated/:id',problem.getrelated);
    route.post('/problem/addrelated/:id',problem.addrelated);
    route.get('/problem/search/:param',problem.search);
    route.get('/problem/macro',problem.macro);
    route.post('/problem/savemasterfile',problem.savemasterfile)
    route.get('/location/get',location.get);
    route.get('/patient/get',patient.get);
    route.get('/patient/get/:id',patient.getinfo);
    route.post('/problem/add/:type',problem.add);
    route.post('/patient/reminders',patient.savereminders);
    route.get('/patient/getraces',patient.getraces);
    route.delete('/patient/delete/reminders/:id',patient.deletereminders);
    route.delete('/patient/delete/patient/:id',patient.deletepatients);
    route.delete('/patient/delete/user/:id',user.deleteuser)
    route.post('/user/setphysician/:id',user.setphysician);
    route.post('/patient/reaction',patient.savereaction);
    route.delete('/patient/delete/reaction/:id',patient.deletereaction);
    route.post('/patient/counter',patient.savepatientcounter);
    route.put('/patient/active',patient.active);
    route.post('/patient/emergency',patient.saveemergency);
    route.post('/patient/updateinfo/:id',patient.updateinfo);
    route.post('/patient/savepharmacy/:patientid',patient.savepharmacy);
    route.post('/patient/saverace',patient.saverace);
    route.get('/patient/searchpharmacy',patient.searchpharmacy);
    route.get('/providers',patient.getproviders);
    route.get('/note/getproblem',problem.get);
    route.get('/note/gettemplate/:id',charttype.get);
    route.get('/cpt/get',cpt.get);
    route.get('/cpt/common',cpt.common);
    route.get('/cpt/favourite',cpt.favourite);
    route.get('/social/get',social.get);
    route.get('/masterfile/get/:id',problem.masterfile);
    route.get('/masterfile/macro/:id',problem.macrofile);
    route.post('/masterfile/add/:sectionid',problem.addmastersection);
    route.delete('/masterfile/delete/:sectionid',problem.deletemastersection);
    route.delete('/masterfileitem/delete',problem.deletemasterfileitem);
    route.post('/masterfileitem/add',problem.addmasterfileitem);
    route.post('/masterfilenode/add',problem.addmasterfilenode);
    route.delete('/masterfilenode/delete',problem.deletemasterfilenode);
    route.post('/statement/add',problem.addstatement);
    route.delete('/statement/delete',problem.deletestatement);
    route.post('/macro/cc/problems',macro.getccproblem);
    route.post('/macro/hpi/problems',macro.gethpiproblems);
    route.get('/macro/problems',macro.getproblems);
    route.get('/macro/symptoms',macro.getsymptoms);
    route.get('/macro/allergy',macro.getallergy);
    route.post('/macro/add',macro.add);
    route.post('/macro/delete',macro.deletemacro);
    route.get('/macro/getdataplan',macro.getdataplan);
    route.get('/masternode/:id',problem.masternode);
    route.get('/diagnostic',problem.getdiagnostic);
    route.get('/getmeds',problem.getmeds);
    route.get('/search/drugs',problem.searchmeds);
    route.get('/alergyinfo/get',problem.alergyinfo);
    route.get('/family/get/:id',family.get);
    route.post('/family/save',family.save);
    route.delete('/family/delete/:id',family.delete);
    route.get('/relation/get',family.getrelation);
    route.post('/master/save',problem.savemaster);
    route.post('/notes/save',note.savenote);   
    route.get('/notes/get/:id',note.get); 
    route.get('/notes/data/:id',note.getdata);
    route.get('/meds/info',meds.info);
    route.get('/meds/detail/:id',meds.detail);
    route.post('/meds/add',meds.addallergy);
    route.post('/meds/addindication/:type/:id',meds.addindication)
    route.post('/dynamic/add',dynamic.save);
    route.get('/dynamic/get/:id',dynamic.get);
    route.get('/dynamic/search',dynamic.search);
    route.get('/plan/search',macro.search);
    
    route.post('/admin/user/search/:type',admin.searchuser);
    route.post('/admin/consultfavourite/:providertype',admin.consultfavourite);
    route.post('/admin/patient/add',admin.addpatient);
    route.get('/admin/location/search',admin.searchlocation);
    route.get('/admin/facilities',admin.searchfacilities);
    route.get('/admin/searchalergy',admin.searchalergy);
    route.get('/admin/searchicd',admin.searchicd);
    route.get('/admin/getsubstance',admin.getsubstance);
    route.get('/admin/physician/:id',admin.getpatientphysician)
    route.get('/admin/physicianinfo/:id',admin.getphysicianinfo);
    route.post('/admin/saveaddress',admin.saveaddress);
    route.delete('/admin/deleteaddress',admin.deleteaddress);
    //admin
    route.post('/user/login',user.login);
    route.get('/user/specialities',user.speciality);
    route.post('/user/add',user.add);
    route.post('/admin/addconsultant',admin.addconsultant);
    route.post('/admin/addlocation',admin.addlocation);
    route.post('/admin/addphysician',admin.addphysician);
    route.post('/admin/addspeciality',admin.addspeciality);
    route.post('/admin/addmeds',admin.addmeds);
    route.post('/admin/addsubstance',admin.addsubstance);
    route.post('/admin/addoption/:type',admin.addoption);
    route.post('/admin/addsocial/:type',admin.addsocial);
    route.post('/admin/deletedata/:type',admin.deletedata);
    route.post('/admin/addassociateddiagnosis',admin.addassociateddiagnosis);
    route.get('/admin/getassociateddiagnosis/:id',admin.getassociateddiagnosis);
    route.get('/admin/searchassociateddiagnosis',admin.searchassociateddiagnosis);
    route.get('/admin/searchallassociateddiagnosis',admin.searchallassociateddiagnosis);
    route.delete('/admin/deleteassociateddiagnosis/:id',admin.deleteassociateddiagnosis);
    route.post('/admin/saveassociatedgroup',admin.saveassociatedgroup);
    route.delete('/admin/deleteassociatedgroup/:id',admin.deleteassociatedgroup);
    route.get('/admin/meds/get',admin.getmeds);
    route.get('/admin/meds/getmedsclass',admin.getmedsclass);
    route.post('/admin/meds/add',admin.addmedsclass);
    route.get('/admin/meds/getmedsfromsubclass/:id',admin.getmedsfromsubclass);
    route.post('/admin/template/save',admin.savetemplate);
    route.get('/admin/template/get',admin.gettemplate);
    route.get('/admin/physician/:id',admin.getphysician);
    route.get('/admin/searchphysician',admin.searchphysician);
    route.post('/admin/saveemployeer',admin.saveemployeer);
    route.delete('/admin/deleteemployeer',admin.deleteemployeer);
    route.get('/admin/getmedsalpha/:alpha',admin.getmedsalpha);
    route.post('/admin/adddefaultreaction/:type',admin.adddefaultreaction);
    route.delete('/admin/deletedefaultreaction/:type',admin.deletedefaultreaction);
    route.post('/admin/updatediagnosisorder',admin.updatediagnosisorder);
}

register();

exports.register = route;